### PR TITLE
Snoop pmove values in updateview for now

### PR DESCRIPTION
**Pull request by newbytf**
This fixes missing CSQC jump sounds

### CODE REVIEW

**Comment by drzel** [comment]
Hey I'm a bit confused with what's going on here. I've just noticed I now how missing jump sounds in csqc jumps (like a lot). I've tried merging this into my local staging branch but it persists. Looking at the code it just looks like you've reoptimised the code with some cached pmove values (good!), but I still have missing jump sounds. How is this supposed to work?

**Comment by newbytf** [comment]
Ah, it works fine on my dev machine.. but I suspect that's symptomatic of what I suspect is the problem: that machine only gets 60fps.  I bet with high fps you're getting lots of interpolation outside of clientcommandframes; enough to miss all the z-edges.  I guess dump it back into update view for now.

That said, I think there are some bugs independent of this in the new code you've pushed; pmove doesn't update health so you won't catch the death edge without converting vel_z to predicted damage and seeing if that puts h negative.

**Comment by drzel** [comment]
Good and bad news.

The good news is that while there is an underlying problem with `input_buttons` not always being accurate, (You can throw an `print(input_buttons, "\n")` into `CSQC_UpdateView()` and watch it change while holding button2), this problem isn't introduced (or fixed) by this PR. It seems like the intersection of this, and some other unknown factor causing jitter will cause the problem. When things are running smoothly (well atleast on my 144hz setup), this issue never results in a missed jump sound. Spoike gave some leads to look into for this which I'll do soon.

The bad news is that this PR reintroduces that bug that caused me to pull the code back into `CSQC_UpdateView()` in the first place. It's pretty easy to test. Slide up a ramp on this branch, you will hear the grind of player/plyrjmp8.wav trying to play every frame. Compare to staging you won't hear it. Hydrobud's example: https://www.twitch.tv/videos/1589429532

**Review by drzel — CHANGES_REQUESTED** [review]
Reintroduces ramp slide grind noise bug.

**Pull request closed without merging**
