### PR TITLE
New feature added to scout scanner spike, assault cannon range and pyro airblast.

### PR DESCRIPTION
**Pull request by haze-au**
1. Scout scanner updated to add a "spike_scan.mdl" (copiled from spike.mdl) - this can be seen by the player and team mates.

This can be then assigned a particle trail via fo-particles.cfg such as the below.

r_part tr_scanner
{
	texture "particles/circle.tga"
	step 45
	scale 13
        scalefactor 2
	die 1
	rgb 128 128 1
        rgbdelta -75 -200 -100
	alpha 0.4
	blend add
	//spawnvel 10
        //spawnorg 0
        nospreadlast
        rotation 0 360 1000 1000
}
r_trail "progs/spike_scan.mdl" tr_scanner

2. HwGug:- Added feature for range on the Assault Cannon (asscanrange - default = 500). Upon reaching the range bullets will have gravity applied via MOVETYPE_TOSS.

3. Pyro:- Applied some fixes to airblast, the find radius is now positioned ahead of the player instead of on player origin, as this is always in front range should change from 400 to 200. Added some server config for 'airblastpushmax' and 'airblastpushmin' to tweak consistency and power.

### CODE REVIEW

**Comment by lordee** [comment]
I'll take a look tonight to give you an example of adding this behind a feature flag so we can enable/disable in game

**Comment by lordee** [comment]
So I think you can just search for "stockfull" in the files to see how it works.  Basically declare a global float (spike_scan?) in qw.qc, do a check for it in client.qc  with cf_getsetting - give it a long name of the same thing and a short name if you want to.  Then test for that float if (!spike_scan) return; or wrap it in if (spike_scan) { do my stuff } and you're sorted.  Test with rcon localinfo spike_scan 1 and see if it enables/disables.

**Comment by haze-au** [comment]
Updates made:

1. Scout scanner:- Cleaned up the unused touch/think functions. Projectile is now MOVETYPE_NOCLIP and disappears on range using nextthink.
2. HwGug:-  Added feature for range on the Assault Cannon (asscanrange). Upon reaching the range bullets will have gravity applied via MOVETYPE_TOSS.

**Review by haze-au — COMMENTED** [review]
ASR changed to ACR for assaultcannonrange

**Comment by haze-au** [comment]
@lordee  @drzel  - Pretty much done making changes here, unless you want something changed.

Last update I have done is the UseAirBlast function. Previously this was a giant findradius from the origin on the player, now the origin is based on aim and the configured airblast range. Range should now be halved as it is placed in front of the player.

Also have introduced some server config for 'airblastpushmin' and 'airblastpushmax' to make the pushval more consistent and less powerful.

**Comment by haze-au** [comment]
As suggested added flag to enable the new pyro airblast.

NOTE: Flags for all 3x new features as below.
serverinfo sss off  //scout scan spike off
serverinfo acr 0 // hw assault cannon range disabled
serverinfo abv2 off // airblast v2 off.

**Pull request merged**
