### PR TITLE
NG and SNG balance changes along with toggles

### PR DESCRIPTION
**Pull request by lordee**
Maybe medic will be a useful class with this change.

### CODE REVIEW

**Comment by drzel** [comment]
This is really awesome @lordee 

We played again tonight. My feeling is medic is a little OP with the current settings and it will require some tweaking. For that reason I think that the old ng settings ought to be default.

The new settings can be configurable with a bool, but perhaps we just let the user pass in their preferred rof and nail speed as localinfos, rather than true or false?

Let me know what you think and if you think you'll have time to implement it - if not I can do it.

This is an awesome contribution - thank you!

**Comment by lordee** [comment]
@drzel Have a look now - made velocity and damage in to variables ng_velocity, ng_damage and sng_damage.  Damage is automatically doubled when old_ng_rof is set to "on".

**Comment by drzel** [comment]
@lordee do we not just want to expose the `ng_rof` as a variable as well? Then no reason for that conditional.

**Comment by lordee** [comment]
While doable (I guess? Only took a quick look) it would require rewriting player_nail1 and player_nail2 in player.qc.  Looks like a bit of work to achieve

**Pull request merged**
